CREATE TABLE AUDITORIA (
     ID_AUDITORIA INT AUTO_INCREMENT PRIMARY KEY,
     USUARIO_AUDITORIA varchar(10) NOT NULL,
     EVENTO_AUDITORIA varchar(15) NULL,
	 TABLA_AUDITORIA varchar(15) NOT NULL,
	 ID_TABLA_AUDITORIA bigint NOT NULL,
	 IP_AUDITORIA varchar(15) NOT NULL,
	 FECHA_AUDITORIA date
);

CREATE TABLE PARAMETRO_NOMINA(
    ID_PARAMETRO_NOMINA TINYINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PARAMETRO VARCHAR(60) NOT NULL,
    VALOR_PARAMETRO FLOAT NOT NULL,
    REMUNERADO CHAR(1) NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A'

);

CREATE TABLE TIPO_NOVEDAD(
    ID_TIPO_NOVEDAD TINYINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(60) NOT NULL,
    ID_PARAMETRO_NOMINA TINYINT NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A',
    FOREIGN KEY (ID_PARAMETRO_NOMINA)
        REFERENCES PARAMETRO_NOMINA (ID_PARAMETRO_NOMINA)
);

CREATE TABLE DEPENDENCIA(
    ID_DEPENDENCIA SMALLINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION_DEPEND VARCHAR(40) NOT NULL
);

CREATE TABLE CJ_COMPENSACION(
    ID_CJ_COMPENSACION SMALLINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION_CMPNSACION VARCHAR(60) NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE PENSION(
    ID_PENSION SMALLINT AUTO_INCREMENT PRIMARY KEY ,
    DESCRIPCION_PNSION VARCHAR(60) NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE EPS(
    ID_EPS SMALLINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION_EPS VARCHAR(60) NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE ARL(
    ID_ARL SMALLINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION_ARL VARCHAR(60) NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE CARGO(
    ID_CARGO MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION_CARGO VARCHAR(60) NOT NULL,
    ID_DEPENDENCIA SMALLINT NOT NULL,
    SALARIO_BASE INT NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A',
    FOREIGN KEY (ID_DEPENDENCIA)
        REFERENCES DEPENDENCIA (ID_DEPENDENCIA)
);

CREATE TABLE PARAMETRO_PRESTACIONES(
    ID_PARAMETRO_PRESTACIONES TINYINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL,
    VALOR_PARAMETRO FLOAT NOT NULL,
    ESTADO CHAR(1) DEFAULT 'A'
);

CREATE TABLE TIPO_CONTRATO(
    ID_TIPO_CONTRATO TINYINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION_TPC VARCHAR(60) NOT NULL,
    ID_PARAMETRO_PRESTACIONES SMALLINT NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO MEDIUMINT PRIMARY KEY,
	PNOMBRE_EMPLEADO varchar(45) NOT NULL,
	SNOMBRE_EMPLEADO varchar(45) DEFAULT NULL,
	PAPELLIDO_EMPLEADO varchar(45) NOT NULL,
	SAPELLIDO_EMPLEADO varchar(45) DEFAULT NULL,
	SALARIO_INTEGRAL CHAR(1),
	FECHA_INGRESO date NOT NULL,
	FECHA_VIGENCIA DATE,
    ID_EPS SMALLINT NOT NULL,
    ID_ARL SMALLINT NOT NULL,
    ID_CARGO MEDIUMINT NOT NULL,
    ID_PENSION SMALLINT NOT NULL,
    ID_TIPO_CONTRATO TINYINT NOT NULL,
    ID_CJ_COMPENSACION SMALLINT NOT NULL,
    ESTADO CHAR(1) NOT NULL DEFAULT 'A',
    FOREIGN KEY (ID_EPS)
        REFERENCES EPS (ID_EPS),
    FOREIGN KEY (ID_ARL)
        REFERENCES ARL (ID_ARL),
    FOREIGN KEY (ID_CARGO)
        REFERENCES CARGO (ID_CARGO),
    FOREIGN KEY (ID_PENSION)
        REFERENCES PENSION (ID_PENSION),
    FOREIGN KEY (ID_TIPO_CONTRATO)
        REFERENCES TIPO_CONTRATO (ID_TIPO_CONTRATO),
    FOREIGN KEY (ID_CJ_COMPENSACION)
        REFERENCES CJ_COMPENSACION (ID_CJ_COMPENSACION)
);

CREATE TABLE NOMINA(
    ID_NOMINA INT AUTO_INCREMENT PRIMARY KEY,
	SUELDO_DEVENGADO MEDIUMINT NOT NULL,
	TRANSPORTE CHAR(1),
	NUM_DIAS_TRABAJADOS SMALLINT NOT NULL,
	SUELDO_TOTAL MEDIUMINT NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE DEFAULT CURDATE(),
	ID_EMPLEADO MEDIUMINT NOT NULL,
	FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE NOVEDAD(
    ID_NOVEDAD MEDIUMINT AUTO_INCREMENT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO MEDIUMINT NOT NULL,
    ID_TIPO_NOVEDAD TINYINT NOT NULL,
    CANTIDAD INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    FOREIGN KEY (ID_TIPO_NOVEDAD)
        REFERENCES TIPO_NOVEDAD (ID_TIPO_NOVEDAD),
    FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO (ID_EMPLEADO)
);