DELIMITER $$
CREATE OR REPLACE PROCEDURE SP_BuscarEmpleados()
BEGIN
   SELECT * FROM arl;
END $$
DELIMITER ;

CALL SP_BuscarEmpleados();

INSERT INTO arl (ID_ARL, DESCRIPCION_ARL) VALUES (1,'Positiva');
INSERT INTO arl (ID_ARL, DESCRIPCION_ARL) VALUES (2,'ARLX');
INSERT INTO arl (ID_ARL, DESCRIPCION_ARL) VALUES (3,'ARLY');
INSERT INTO arl (ID_ARL, DESCRIPCION_ARL) VALUES (4,'ARLZ');
